# Stage 1: Build
FROM node:22-alpine AS builder

WORKDIR /app

# Install all dependencies including devDependencies
COPY package*.json ./
RUN npm install

# Copy source files
COPY . .

# Run build tasks
RUN npm run prisma:generate
RUN npm run build

# Stage 2: Production
FROM node:22-alpine

WORKDIR /app

# Copy only the package files and install production dependencies
COPY  docker-entrypoint.sh ./
COPY package*.json ./
COPY assets ./assets
COPY templates ./templates

# Copy built output and any runtime files from builder
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma   
COPY --from=builder /app/node_modules/ ./node_modules/ 


EXPOSE 9999

CMD [ "./docker-entrypoint.sh" ]
